In [1]:
import re

In [2]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [3]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [4]:
len(text)

205

In [5]:
num_characters = 34 #33 буквы + пробел

In [6]:
import keras
from keras.preprocessing.text import Tokenizer

In [7]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [8]:
tokenizer.fit_on_texts(text)

In [9]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [10]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [11]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [13]:
import numpy as np

In [14]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [15]:
len(X)

199

In [16]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [17]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
from keras.layers import *
from keras.models import Sequential

In [19]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 5s 78ms/step - loss: 3.4163 - accuracy: 0.0754
Epoch 2/100
7/7 [==============================] - 0s 41ms/step - loss: 2.4471 - accuracy: 0.3166
Epoch 3/100
7/7 [==============================] - 0s 39ms/step - loss: 1.8734 - accuracy: 0.5126
Epoch 4/100
7/7 [==============================] - 0s 57ms/step - loss: 1.4914 - accuracy: 0.5628
Epoch 5/100
7/7 [==============================] - 0s 35ms/step - loss: 1.2290 - accuracy: 0.6533
Epoch 6/100
7/7 [==============================] - 0s 40ms/step - loss: 1.0574 - accuracy: 0.6784
Epoch 7/100
7/7 [==============================] - 0s 46ms/step - loss: 0.8339 - accuracy: 0.7588
Epoch 8/100
7/7 [==============================] - 1s 71ms/step - loss: 0.7382 - accuracy: 0.8241
Epoch 9/100
7/7 [==============================] - 0s 52ms/step - loss: 0.6050 - accuracy: 0.8744
Epoch 10/100
7/7 [==============================] - 1s 85ms/step - loss: 0.5456 - accuracy: 0.8693
Epoch 11/100
7/7 [=

In [21]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [22]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 21ms/step
утренноитовдостогась отлечных пезулеватовп липер оеротер


# Слова


In [179]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts2 = f.read()
    texts2 = texts2.replace('\ufeff', '') # убираем первый невидимый символ

In [180]:
maxWordsCount2 = 1000
tokenizer2 = Tokenizer(num_words=maxWordsCount2, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer2.fit_on_texts([texts2])

In [181]:
tokenizer2.word_index

{'вы': 1,
 'в': 2,
 'понедельник': 3,
 'лучший': 4,
 'ответ': 5,
 'на': 6,
 'проблемы': 7,
 'которые': 8,
 'возникли': 9,
 'думайте': 10,
 'позитивно': 11,
 'и': 12,
 'верьте': 13,
 'свою': 14,
 'способность': 15,
 'достигать': 16,
 'отличных': 17,
 'результатов': 18,
 'если': 19,
 'смогли': 20,
 'подняться': 21,
 'с': 22,
 'постели': 23,
 'значит': 24,
 'супер': 25,
 'герой': 26}

In [182]:
dist = list(tokenizer2.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [183]:
data2 = tokenizer2.texts_to_sequences([texts2])

print(data2)

[[1, 4, 5, 6, 7, 8, 9, 2, 3, 10, 11, 12, 13, 2, 14, 15, 16, 17, 18, 19, 1, 20, 2, 3, 21, 22, 23, 24, 1, 25, 26]]


In [184]:
# data2

In [185]:
len(data2[0])

31

In [186]:
res2 = keras.utils.to_categorical(data2[0], num_classes=maxWordsCount2)
res2

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [187]:
inp_words2 = 3
n = res2.shape[0]-inp_words2

In [188]:
X2 = np.array([res2[i:i+inp_words2, :] for i in range(n)])
Y2 = res2[inp_words2:]

In [189]:
# https://github.com/allseenn/neuronet/blob/f3049edbe81f67d46557b8078fa603a73d667a6f/05.Tasks/hw05neuro.ipynb#L22

# model = Sequential()
# model.add(Input((inp_words2, maxWordsCount2)))
# model.add(SimpleRNN(128, activation='tanh'))
# model.add(Dense(maxWordsCount2, activation='softmax'))
# model.summary()

# model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


from tensorflow.keras.layers import Dropout

model2 = Sequential()
model2.add(Input((inp_words2, maxWordsCount2)))
model2.add(SimpleRNN(256, activation='tanh', return_sequences=True))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(SimpleRNN(256, activation='tanh'))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(Dense(maxWordsCount2, activation='softmax'))
model2.summary()
model2.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_12 (SimpleRNN)   (None, 3, 256)            321792    
                                                                 
 dropout_10 (Dropout)        (None, 3, 256)            0         
                                                                 
 simple_rnn_13 (SimpleRNN)   (None, 256)               131328    
                                                                 
 dropout_11 (Dropout)        (None, 256)               0         
                                                                 
 dense_7 (Dense)             (None, 1000)              257000    
                                                                 
Total params: 710120 (2.71 MB)
Trainable params: 710120 (2.71 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [190]:
history = model2.fit(X2, Y2, batch_size=32, epochs=25)

Epoch 1/25
1/1 [==============================] - 3s 3s/step - loss: 6.9103 - accuracy: 0.0000e+00
Epoch 2/25
1/1 [==============================] - 0s 27ms/step - loss: 6.8027 - accuracy: 0.0357
Epoch 3/25
1/1 [==============================] - 0s 26ms/step - loss: 6.6702 - accuracy: 0.4643
Epoch 4/25
1/1 [==============================] - 0s 31ms/step - loss: 6.5390 - accuracy: 0.8214
Epoch 5/25
1/1 [==============================] - 0s 27ms/step - loss: 6.4091 - accuracy: 0.9643
Epoch 6/25
1/1 [==============================] - 0s 26ms/step - loss: 6.2636 - accuracy: 0.9643
Epoch 7/25
1/1 [==============================] - 0s 33ms/step - loss: 6.0952 - accuracy: 0.9643
Epoch 8/25
1/1 [==============================] - 0s 26ms/step - loss: 5.9129 - accuracy: 0.9643
Epoch 9/25
1/1 [==============================] - 0s 27ms/step - loss: 5.7131 - accuracy: 1.0000
Epoch 10/25
1/1 [==============================] - 0s 25ms/step - loss: 5.4853 - accuracy: 0.9643
Epoch 11/25
1/1 [==========

In [210]:
# def buildPhrase2(texts, str_len=20):
#     res = texts

#     tokenizer2 = Tokenizer(num_words=maxWordsCount2, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',lower=True, split=' ', char_level=False)
#     tokenizer2.fit_on_texts([texts])
#     dataa = tokenizer2.texts_to_sequences([texts])
#     # print(f"{tokenizer2.texts_to_sequences([texts])[0] = }")

#     # Проверяем, что dataa не пустой
#     if dataa:
#         dataa = dataa[0]  # Выбираем первый элемент, так как texts_to_sequences возвращает список

#         # Проверяем, что dataa не пустой
#         if dataa:
#             # x = []
#             # for j in range(i, i+inp_chars):
#             #   x.append(tokenizer2.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

#             for i in range(str_len):
#                 x = keras.utils.to_categorical(dataa[i: i+inp_words2], num_classes=maxWordsCount2)

#                 # Проверяем, что x не пустой
#                 if x.size != 0:
#                     inp = x.reshape(1, inp_words2, maxWordsCount2)  # преобразуем в One-Hot-encod
#                     pred = model2.predict(inp)  # предсказываем OHE четвертого символа с использованием model2
#                     indx = pred.argmax(axis=1)[0]
#                     data2.append(indx)
#                     res += " " + tokenizer2.index_word[indx]  # дописываем строку
#                 else:
#                     break  # Прерываем цикл, если x пустой
#         else:
#             print("Ошибка: пустые данные после токенизации")
#     else:
#         print("Ошибка: пустые данные после токенизации")

#     return res

In [202]:
# for i in range(1):
#     x = keras.utils.to_categorical(data[i: i+inp_words2], num_classes=maxWordsCount2)
#
# x.shape

In [211]:
# res = buildPhrase2(["позитивно и верьте"])
# print(res)

# # https://proproprogs.ru/neural_network/vvedenie-v-rekurrentnye-neyronnye-seti

ValueError: cannot reshape array of size 1000 into shape (1,3,1000)

# https://github.com/allseenn/neuronet/blob/f3049edbe81f67d46557b8078fa603a73d667a6f/05.Tasks/hw05neuro.ipynb#L22

---

---

In [216]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text2 = f.read()
    text2 = text2.replace('\ufeff', '') # убираем первый невидимый символ

In [228]:
maxWordsCount2 = 10000
tokenizer2 = Tokenizer(num_words=maxWordsCount2, filters='!–"—#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer2.fit_on_texts([text2])

In [229]:
tokenizer2.word_index

{'вы': 1,
 'в': 2,
 'понедельник': 3,
 'лучший': 4,
 'ответ': 5,
 'на': 6,
 'проблемы': 7,
 'которые': 8,
 'возникли': 9,
 'думайте': 10,
 'позитивно': 11,
 'и': 12,
 'верьте': 13,
 'свою': 14,
 'способность': 15,
 'достигать': 16,
 'отличных': 17,
 'результатов': 18,
 'если': 19,
 'смогли': 20,
 'подняться': 21,
 'с': 22,
 'постели': 23,
 'значит': 24,
 'супер': 25,
 'герой': 26}

In [230]:
data2 = tokenizer2.texts_to_sequences([text2])

In [231]:
res2 = keras.utils.to_categorical(data2[0], num_classes=maxWordsCount2)
res2

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [232]:
inp_words2 = 3
n2 = res2.shape[0]-inp_words2

In [233]:
X2 = np.array([res2[i:i+inp_words2, :] for i in range(n2)])
Y2 = res2[inp_words2:]

In [234]:
from tensorflow.keras.layers import Dropout

model2 = Sequential()
model2.add(Input((inp_words2, maxWordsCount2)))
model2.add(SimpleRNN(256, activation='tanh', return_sequences=True))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(SimpleRNN(256, activation='tanh'))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(Dense(maxWordsCount2, activation='softmax'))
model2.summary()
model2.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_16 (SimpleRNN)   (None, 3, 256)            2625792   
                                                                 
 dropout_14 (Dropout)        (None, 3, 256)            0         
                                                                 
 simple_rnn_17 (SimpleRNN)   (None, 256)               131328    
                                                                 
 dropout_15 (Dropout)        (None, 256)               0         
                                                                 
 dense_9 (Dense)             (None, 10000)             2570000   
                                                                 
Total params: 5327120 (20.32 MB)
Trainable params: 5327120 (20.32 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [235]:
model2.fit(X2, Y2, batch_size=32, epochs=25)

Epoch 1/25
1/1 [==============================] - 2s 2s/step - loss: 9.2078 - accuracy: 0.0000e+00
Epoch 2/25
1/1 [==============================] - 0s 105ms/step - loss: 9.1864 - accuracy: 0.0357
Epoch 3/25
1/1 [==============================] - 0s 102ms/step - loss: 9.1580 - accuracy: 0.7857
Epoch 4/25
1/1 [==============================] - 0s 109ms/step - loss: 9.1264 - accuracy: 0.9643
Epoch 5/25
1/1 [==============================] - 0s 128ms/step - loss: 9.0888 - accuracy: 0.9643
Epoch 6/25
1/1 [==============================] - 0s 111ms/step - loss: 9.0421 - accuracy: 0.9286
Epoch 7/25
1/1 [==============================] - 0s 122ms/step - loss: 8.9808 - accuracy: 0.9286
Epoch 8/25
1/1 [==============================] - 0s 107ms/step - loss: 8.8900 - accuracy: 0.8929
Epoch 9/25
1/1 [==============================] - 0s 104ms/step - loss: 8.7756 - accuracy: 0.7857
Epoch 10/25
1/1 [==============================] - 0s 113ms/step - loss: 8.6038 - accuracy: 0.6786
Epoch 11/25
1/1 [=

In [258]:
from keras.utils import to_categorical

def buildPhrase2(phrase, str_len=10):
    res = phrase
    data = tokenizer2.texts_to_sequences([phrase])[0]
    used_words = set(data)  # Множество уже использованных слов
    prev_word = data[-1]  # Предыдущее слово
    for i in range(str_len):
        # Получаем вероятности для предсказания следующего слова
        x = to_categorical(data[i: i + inp_words2], num_classes=maxWordsCount2)
        inp = x.reshape(1, inp_words2, maxWordsCount2)
        pred = model2.predict(inp)[0]

        # Убираем вероятности для уже использованных слов
        pred_filtered = [p if idx not in used_words else 0 for idx, p in enumerate(pred)]
        # Убираем вероятности для предыдущего слова
        pred_filtered[prev_word] = 0

        # Выбираем индекс следующего слова с учетом фильтрации
        indx = np.argmax(pred_filtered)
        data.append(indx)

        res += " " + tokenizer2.index_word[indx]
        used_words.add(indx)  # Добавляем новое слово в множество использованных слов
        prev_word = indx  # Обновляем предыдущее слово

    return res

In [259]:
resEnd = buildPhrase2("верьте в себя")

ValueError: cannot reshape array of size 20000 into shape (1,3,10000)

In [260]:
resEnd

'верьте в себя'