In [358]:
import re

In [359]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [360]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [361]:
len(text)

205

In [362]:
num_characters = 34 #33 буквы + пробел

In [363]:
import keras
from keras.preprocessing.text import Tokenizer

In [364]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [365]:
tokenizer.fit_on_texts(text)

In [366]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [367]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [368]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [369]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [370]:
import numpy as np

In [371]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [372]:
len(X)

199

In [373]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [374]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [375]:
from keras.layers import *
from keras.models import Sequential

In [376]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_14 (SimpleRNN)   (None, 500)               267500    
                                                                 
 dense_14 (Dense)            (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [377]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 15ms/step - loss: 3.3770 - accuracy: 0.1156
Epoch 2/100
7/7 [==============================] - 0s 17ms/step - loss: 2.4515 - accuracy: 0.2814
Epoch 3/100
7/7 [==============================] - 0s 15ms/step - loss: 1.9580 - accuracy: 0.4523
Epoch 4/100
7/7 [==============================] - 0s 15ms/step - loss: 1.5500 - accuracy: 0.5025
Epoch 5/100
7/7 [==============================] - 0s 16ms/step - loss: 1.2540 - accuracy: 0.6382
Epoch 6/100
7/7 [==============================] - 0s 15ms/step - loss: 1.0186 - accuracy: 0.7236
Epoch 7/100
7/7 [==============================] - 0s 17ms/step - loss: 0.9212 - accuracy: 0.7387
Epoch 8/100
7/7 [==============================] - 0s 16ms/step - loss: 0.7894 - accuracy: 0.7839
Epoch 9/100
7/7 [==============================] - 0s 14ms/step - loss: 0.6400 - accuracy: 0.8392
Epoch 10/100
7/7 [==============================] - 0s 15ms/step - loss: 0.6007 - accuracy: 0.8241
Epoch 11/100
7/7 [=

In [378]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [379]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 26ms/step
утренновтовн  и верьте в свою способность достигать отли


# Слова


In [409]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts2 = f.read()
    texts2 = texts2.replace('\ufeff', '') # убираем первый невидимый символ

In [410]:
maxWordsCount2 = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts2])

In [411]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [412]:
data = tokenizer.texts_to_sequences([texts2])

print(data)

[[1, 4, 5, 6, 7, 8, 9, 2, 3, 10, 11, 12, 13, 2, 14, 15, 16, 17, 18, 19, 1, 20, 2, 3, 21, 22, 23, 24, 1, 25, 26]]


In [413]:
# data

In [414]:
len(data[0])

31

In [415]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(31, 1000)


In [416]:
inp_words2 = 3
n = res.shape[0]-inp_words

In [417]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [418]:
# https://github.com/allseenn/neuronet/blob/f3049edbe81f67d46557b8078fa603a73d667a6f/05.Tasks/hw05neuro.ipynb#L22

# model = Sequential()
# model.add(Input((inp_words, maxWordsCount)))
# model.add(SimpleRNN(128, activation='tanh'))
# model.add(Dense(maxWordsCount, activation='softmax'))
# model.summary()

# model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


from tensorflow.keras.layers import Dropout

model2 = Sequential()
model2.add(Input((inp_words2, maxWordsCount2)))
model2.add(SimpleRNN(256, activation='tanh', return_sequences=True))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(SimpleRNN(256, activation='tanh'))
model2.add(Dropout(0.2))  # Добавляем dropout для уменьшения переобучения
model2.add(Dense(maxWordsCount2, activation='softmax'))
model2.summary()
model2.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_17 (SimpleRNN)   (None, 3, 256)            321792    
                                                                 
 dropout (Dropout)           (None, 3, 256)            0         
                                                                 
 simple_rnn_18 (SimpleRNN)   (None, 256)               131328    
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_17 (Dense)            (None, 1000)              257000    
                                                                 
Total params: 710120 (2.71 MB)
Trainable params: 710120 (2.71 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [419]:
history = model2.fit(X, Y, batch_size=32, epochs=59)

Epoch 1/59
1/1 [==============================] - 2s 2s/step - loss: 6.9144 - accuracy: 0.0000e+00
Epoch 2/59
1/1 [==============================] - 0s 30ms/step - loss: 6.7738 - accuracy: 0.1071
Epoch 3/59
1/1 [==============================] - 0s 30ms/step - loss: 6.6682 - accuracy: 0.3929
Epoch 4/59
1/1 [==============================] - 0s 32ms/step - loss: 6.5296 - accuracy: 0.8214
Epoch 5/59
1/1 [==============================] - 0s 31ms/step - loss: 6.3980 - accuracy: 1.0000
Epoch 6/59
1/1 [==============================] - 0s 29ms/step - loss: 6.2213 - accuracy: 1.0000
Epoch 7/59
1/1 [==============================] - 0s 29ms/step - loss: 6.0766 - accuracy: 1.0000
Epoch 8/59
1/1 [==============================] - 0s 32ms/step - loss: 5.9103 - accuracy: 1.0000
Epoch 9/59
1/1 [==============================] - 0s 29ms/step - loss: 5.6876 - accuracy: 0.9643
Epoch 10/59
1/1 [==============================] - 0s 30ms/step - loss: 5.4466 - accuracy: 0.9643
Epoch 11/59
1/1 [==========

In [420]:
def buildPhrase2(texts : str, str_len = 20):
  res = texts
  dataa = tokenizer.texts_to_sequences([texts])[0]
  for i in range(str_len):
    x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
    inp = x.reshape(1, inp_words, maxWordsCount)
    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    indx = pred.argmax(axis=1)[0]
    data.append(indx)
    res += " " + tokenizer.index_word[indx] # дописываем строку
  return res

In [422]:
for i in range(1):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount)

In [423]:
x.shape

(1, 31, 1000)

In [424]:
# res = buildPhrase2("позитив добавляет годы")
# print(res)


# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-319-c4bf87fabd6e> in <cell line: 1>()
# ----> 1 res = buildPhrase2("позитив добавляет годы")
#       2 print(res)

# <ipython-input-316-b7a752cdecfb> in buildPhrase2(texts, str_len)
#       4   for i in range(str_len):
#       5     x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
# ----> 6     inp = x.reshape(1, inp_words, maxWordsCount)
#       7     pred = model.predict( inp ) # предсказываем OHE четвертого символа
#       8     indx = pred.argmax(axis=1)[0]

# ValueError: cannot reshape array of size 0 into shape (1,3,1000)


# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-424-ebad082d41fe> in <cell line: 1>()
# ----> 1 res = buildPhrase2("позитив добавляет годы")
#       2 print(res)
#       3
#       4
#       5 # ---------------------------------------------------------------------------

# <ipython-input-420-b7a752cdecfb> in buildPhrase2(texts, str_len)
#       4   for i in range(str_len):
#       5     x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
# ----> 6     inp = x.reshape(1, inp_words, maxWordsCount)
#       7     pred = model.predict( inp ) # предсказываем OHE четвертого символа
#       8     indx = pred.argmax(axis=1)[0]

# ValueError: cannot reshape array of size 0 into shape (1,3,1000)

ValueError: cannot reshape array of size 0 into shape (1,3,1000)

In [425]:
texts = "позитив добавляет годы"
res = texts
dataa = tokenizer.texts_to_sequences([texts])[0]
for i in range(str_len):
  x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
  inp = x.reshape(1, inp_words, maxWordsCount)
  pred = model.predict( inp ) # предсказываем OHE четвертого символа
  indx = pred.argmax(axis=1)[0]
  data.append(indx)
  res += " " + tokenizer.index_word[indx] # дописываем строку
print(res)

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-396-799b6d235b47> in <cell line: 4>()
#       4 for i in range(str_len):
#       5   x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
# ----> 6   inp = x.reshape(1, inp_words, maxWordsCount)
#       7   pred = model.predict( inp ) # предсказываем OHE четвертого символа
#       8   indx = pred.argmax(axis=1)[0]

# ValueError: cannot reshape array of size 0 into shape (1,3,1000)


# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-425-8e1eb0d2da86> in <cell line: 4>()
#       4 for i in range(str_len):
#       5   x = keras.utils.to_categorical(dataa[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
# ----> 6   inp = x.reshape(1, inp_words, maxWordsCount)
#       7   pred = model.predict( inp ) # предсказываем OHE четвертого символа
#       8   indx = pred.argmax(axis=1)[0]

# ValueError: cannot reshape array of size 0 into shape (1,3,1000)


ValueError: cannot reshape array of size 0 into shape (1,3,1000)